// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JP_FrontWebAPI.Models;

public partial class Admin
{
    public int AdminId { get; set; }

    public string AdminName { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string ImagePath { get; set; }

    public bool AdminManageStatus { get; set; }

    public bool MemberManageStatus { get; set; }

    public bool IniteraryManageStatus { get; set; }

    public bool ShipmentManageStatus { get; set; }

    public bool OrderManageStatus { get; set; }

    public bool CouponManageStatus { get; set; }

    public bool CommentManageStatus { get; set; }

    public bool BlogManageStatus { get; set; }
}