// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JP_FrontWebAPI.Models;

public partial class Itinerary
{
    public int ItinerarySystemId { get; set; }

    public string ItineraryId { get; set; }

    public string ItineraryName { get; set; }

    public int? ActivitySystemId { get; set; }

    public int Stock { get; set; }

    public decimal Price { get; set; }

    public int? AreaSystemId { get; set; }

    public string ItineraryDetail { get; set; }

    public string ItineraryBrief { get; set; }

    public string ItineraryNotes { get; set; }

    public virtual Activity ActivitySystem { get; set; }

    public virtual Area AreaSystem { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<ItineraryDate> ItineraryDates { get; set; } = new List<ItineraryDate>();

    public virtual ICollection<MyCollection> MyCollections { get; set; } = new List<MyCollection>();
}