// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JP_FrontWebAPI.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string OrderNumber { get; set; }

    public int? MemberId { get; set; }

    public DateTime? OrderTime { get; set; }

    public int? PaymentMethodId { get; set; }

    public DateTime? PaymentTime { get; set; }

    public int? OrderStatusId { get; set; }

    public int? CouponId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Remarks { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual ICollection<ItineraryOrderItem> ItineraryOrderItems { get; set; } = new List<ItineraryOrderItem>();

    public virtual Member Member { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual ICollection<TicketOrderItem> TicketOrderItems { get; set; } = new List<TicketOrderItem>();
}