// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using prjJapanTravel_BackendMVC.MetaDatas;
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Image
{
    public List<IFormFile> ItineraryPics { get; set; }
}