// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

[Table("Admin")]
public partial class Admin
{
    [Key]
    [Column("AdminID")]
    public int AdminId { get; set; }

    [Required]
    [StringLength(50)]
    public string AdminName { get; set; }

    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("imagePath")]
    [StringLength(50)]
    public string ImagePath { get; set; }

    public bool AdminManageStatus { get; set; }

    public bool MemberManageStatus { get; set; }

    public bool IniteraryManageStatus { get; set; }

    public bool ShipmentManageStatus { get; set; }

    public bool OrderManageStatus { get; set; }

    public bool CouponManageStatus { get; set; }

    public bool CommentManageStatus { get; set; }

    public bool BlogManageStatus { get; set; }
}