// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class ArticlePic
{
    public int PicNumber { get; set; }

    public int ArticleNumber { get; set; }

    public string PicDescription { get; set; }

    public string PicPath { get; set; }

    public virtual ArticleMain ArticleNumberNavigation { get; set; }
}