// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

[Table("Article狀態")]
public partial class Article狀態
{
    [StringLength(10)]
    public string 狀態名稱 { get; set; }

    [Key]
    public int 文章狀態編號 { get; set; }

    [InverseProperty("文章狀態編號Navigation")]
    public virtual ICollection<Article文章> Article文章s { get; set; } = new List<Article文章>();
}