// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Article文章
{
    public int 文章編號 { get; set; }

    public int 會員id { get; set; }

    public string 文章標題 { get; set; }

    public DateOnly 發布時間 { get; set; }

    public int 文章狀態編號 { get; set; }

    public virtual ICollection<Article圖片> Article圖片s { get; set; } = new List<Article圖片>();

    public virtual ICollection<文章hashtag中介表> 文章hashtag中介表s { get; set; } = new List<文章hashtag中介表>();

    public virtual Article狀態 文章狀態編號Navigation { get; set; }
}