// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class ArticleStatus
{
    public string StatusName { get; set; }

    public int StatusNumber { get; set; }

    public virtual ICollection<ArticleMain> ArticleMains { get; set; } = new List<ArticleMain>();
}