// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Article圖片
{
    public int 圖片編號 { get; set; }

    public int 文章編號 { get; set; }

    public byte[] 圖片 { get; set; }

    public string 圖片說明 { get; set; }

    public virtual Article文章 文章編號Navigation { get; set; }
}