// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Article狀態
{
    public string 狀態名稱 { get; set; }

    public int 文章狀態編號 { get; set; }

    public virtual ICollection<Article文章> Article文章s { get; set; } = new List<Article文章>();
}