// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponName { get; set; }

    public decimal Discount { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public bool CouponStatus { get; set; }

    public virtual ICollection<ItineraryOrder> ItineraryOrders { get; set; } = new List<ItineraryOrder>();

    public virtual ICollection<MemberCouponList> MemberCouponLists { get; set; } = new List<MemberCouponList>();

    public virtual ICollection<TicketOrder> TicketOrders { get; set; } = new List<TicketOrder>();
}