// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

[Table("DetailSpot明細景點")]
public partial class DetailSpot明細景點
{
    [Key]
    public int 明細景點編號 { get; set; }

    public int? 明細編號 { get; set; }

    public int? 景點編號 { get; set; }
}