// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Entourage
{
    public int EntourageId { get; set; }

    public int? MemberId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool? Gender { get; set; }

    public DateOnly? Birthday { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual Member Member { get; set; }
}