// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class HashtagMain
{
    public int HashtagNumber { get; set; }

    public string HashtagName { get; set; }
}