// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Hashtag
{
    public int Hashtag編號 { get; set; }

    public string Hashtag名稱 { get; set; }

    public virtual ICollection<文章hashtag中介表> 文章hashtag中介表s { get; set; } = new List<文章hashtag中介表>();
}