// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

[Table("Image")]
public partial class Image
{
    [Key]
    public int ItineraryPicSystemId { get; set; }

    [Column(TypeName = "image")]
    public byte[] ImagePath { get; set; }

    [StringLength(50)]
    public string ImageName { get; set; }

    public string ImageDetail { get; set; }
}