// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Itinerary
{
    public int ItinerarySystemId { get; set; }

    public string ItineraryId { get; set; }

    public string ItineraryName { get; set; }

    public int? ActivitySystemId { get; set; }

    public int? Stock { get; set; }

    public decimal? Price { get; set; }

    public int? ThemeSystemId { get; set; }

    public int? AreaSystemId { get; set; }

    public int? ItineraryPicSystemId { get; set; }

    public string ItineraryDetail { get; set; }

    public string ItineraryBrief { get; set; }

    public string ItineraryNotes { get; set; }

    public virtual Activity ActivitySystem { get; set; }

    public virtual Area AreaSystem { get; set; }

    public virtual ICollection<ItineraryDate> ItineraryDates { get; set; } = new List<ItineraryDate>();

    public virtual Image ItineraryPicSystem { get; set; }

    public virtual ICollection<MyCollection> MyCollections { get; set; } = new List<MyCollection>();

    public virtual Theme ThemeSystem { get; set; }
}