// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

public partial class JapanTravelContext : DbContext
{
    public JapanTravelContext(DbContextOptions<JapanTravelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<Article圖片> Article圖片s { get; set; }

    public virtual DbSet<Article文章> Article文章s { get; set; }

    public virtual DbSet<Article狀態> Article狀態s { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<DetailSpot明細景點> DetailSpot明細景點s { get; set; }

    public virtual DbSet<Hashtag> Hashtags { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<Itinerary> Itineraries { get; set; }

    public virtual DbSet<ItineraryDate> ItineraryDates { get; set; }

    public virtual DbSet<ItineraryOrder> ItineraryOrders { get; set; }

    public virtual DbSet<ItinerarytoPic> ItinerarytoPics { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberCouponList> MemberCouponLists { get; set; }

    public virtual DbSet<MemberLevel> MemberLevels { get; set; }

    public virtual DbSet<MemberStatus> MemberStatuses { get; set; }

    public virtual DbSet<MyCollection> MyCollections { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<Passenger> Passengers { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }

    public virtual DbSet<Port> Ports { get; set; }

    public virtual DbSet<Route> Routes { get; set; }

    public virtual DbSet<RouteImage> RouteImages { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Theme> Themes { get; set; }

    public virtual DbSet<TicketOrder> TicketOrders { get; set; }

    public virtual DbSet<TicketOrderItem> TicketOrderItems { get; set; }

    public virtual DbSet<文章hashtag中介表> 文章hashtag中介表s { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.ActivitySystemId).HasName("PK_Spot景點");
        });

        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK_Admin管理員");
        });

        modelBuilder.Entity<Area>(entity =>
        {
            entity.HasKey(e => e.AreaSystemId).HasName("PK_Area地區");
        });

        modelBuilder.Entity<Article圖片>(entity =>
        {
            entity.Property(e => e.圖片編號).ValueGeneratedNever();
            entity.Property(e => e.文章編號).ValueGeneratedOnAdd();

            entity.HasOne(d => d.文章編號Navigation).WithMany(p => p.Article圖片s)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Article圖片_Article文章");
        });

        modelBuilder.Entity<Article文章>(entity =>
        {
            entity.HasOne(d => d.文章狀態編號Navigation).WithMany(p => p.Article文章s)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Article文章_Article狀態");
        });

        modelBuilder.Entity<Article狀態>(entity =>
        {
            entity.Property(e => e.狀態名稱).IsFixedLength();
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponId).HasName("PK_Coupon優惠券");
        });

        modelBuilder.Entity<Itinerary>(entity =>
        {
            entity.HasKey(e => e.ItinerarySystemId).HasName("PK_Itinerary行程_1");

            entity.HasOne(d => d.ActivitySystem).WithMany(p => p.Itineraries).HasConstraintName("FK_Itinerary行程_Activity體驗");

            entity.HasOne(d => d.AreaSystem).WithMany(p => p.Itineraries).HasConstraintName("FK_Itinerary行程_Area地區");

            entity.HasOne(d => d.ThemeSystem).WithMany(p => p.Itineraries).HasConstraintName("FK_Itinerary行程_Theme主題1");
        });

        modelBuilder.Entity<ItineraryDate>(entity =>
        {
            entity.HasKey(e => e.ItineraryDateSystemId).HasName("PK_ItineraryTime行程批次");

            entity.HasOne(d => d.ItinerarySystem).WithMany(p => p.ItineraryDates).HasConstraintName("FK_ItineraryTime行程批次_Itinerary行程");
        });

        modelBuilder.Entity<ItineraryOrder>(entity =>
        {
            entity.HasKey(e => e.ItineraryOrderId).HasName("PK_訂單資料_行程");

            entity.HasOne(d => d.Coupon).WithMany(p => p.ItineraryOrders).HasConstraintName("FK_ItineraryOrder_Coupon");

            entity.HasOne(d => d.ItineraryDateSystem).WithMany(p => p.ItineraryOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItineraryOrder_ItineraryDate");

            entity.HasOne(d => d.Member).WithMany(p => p.ItineraryOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItineraryOrder_Member");

            entity.HasOne(d => d.OrderStatus).WithMany(p => p.ItineraryOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItineraryOrder_OrderStatus");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.ItineraryOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItineraryOrder_PaymentMethod");

            entity.HasOne(d => d.PaymentStatus).WithMany(p => p.ItineraryOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItineraryOrder_PaymentStatus");
        });

        modelBuilder.Entity<ItinerarytoPic>(entity =>
        {
            entity.HasOne(d => d.ItineraryPicSystem).WithMany().HasConstraintName("FK_ItinerarytoPic_Image");

            entity.HasOne(d => d.ItinerarySystem).WithMany().HasConstraintName("FK_ItinerarytoPic_Itinerary");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasOne(d => d.City).WithMany(p => p.Members).HasConstraintName("FK_Member_City1");

            entity.HasOne(d => d.MemberLevel).WithMany(p => p.Members)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Member_MemberLevel");

            entity.HasOne(d => d.MemberStatus).WithMany(p => p.Members)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Member_MemberStatus");
        });

        modelBuilder.Entity<MemberCouponList>(entity =>
        {
            entity.HasKey(e => e.MemberCouponId).HasName("PK_betwMemberCoupon會員優惠券中繼表");

            entity.HasOne(d => d.Coupon).WithMany(p => p.MemberCouponLists)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_betwMemberCoupon_Coupon優惠券");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberCouponLists)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_betwMemberCoupon會員優惠券中繼表_Member會員");
        });

        modelBuilder.Entity<MyCollection>(entity =>
        {
            entity.HasKey(e => e.MyCollectionId).HasName("PK_MyFavorite我的最愛");

            entity.HasOne(d => d.Itinerary).WithMany(p => p.MyCollections)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MyFavorite我的最愛_Itinerary行程");

            entity.HasOne(d => d.Member).WithMany(p => p.MyCollections)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MyFavorite我的最愛_Member");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.OrderStatusId).HasName("PK_訂單狀態");
        });

        modelBuilder.Entity<Passenger>(entity =>
        {
            entity.HasKey(e => e.PassengerId).HasName("PK_航班旅客資料");

            entity.Property(e => e.PassengerId).ValueGeneratedNever();

            entity.HasOne(d => d.TicketOrderItem).WithMany(p => p.Passengers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Passenger_TicketOrderItem");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethodId).HasName("PK_付款方式");
        });

        modelBuilder.Entity<PaymentStatus>(entity =>
        {
            entity.HasKey(e => e.PaymentStatusId).HasName("PK_付款狀態");
        });

        modelBuilder.Entity<Port>(entity =>
        {
            entity.HasKey(e => e.PortId).HasName("PK_tPort");
        });

        modelBuilder.Entity<Route>(entity =>
        {
            entity.HasKey(e => e.RouteId).HasName("PK_tRoutes");

            entity.HasOne(d => d.DestinationPort).WithMany(p => p.RouteDestinationPorts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tRoutes_tPort1");

            entity.HasOne(d => d.OriginPort).WithMany(p => p.RouteOriginPorts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tRoutes_tPort");
        });

        modelBuilder.Entity<RouteImage>(entity =>
        {
            entity.HasKey(e => e.RouteImageId).HasName("PK_tImages");

            entity.HasOne(d => d.Route).WithMany(p => p.RouteImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tImages_tRoutes");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("PK_tSchedules");

            entity.HasOne(d => d.Route).WithMany(p => p.Schedules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tSchedules_tRoutes");
        });

        modelBuilder.Entity<Theme>(entity =>
        {
            entity.HasKey(e => e.ThemeSystemId).HasName("PK_Theme主題");
        });

        modelBuilder.Entity<TicketOrder>(entity =>
        {
            entity.HasKey(e => e.TicketOrderId).HasName("PK_訂單資料_航班");

            entity.HasOne(d => d.Coupon).WithMany(p => p.TicketOrders).HasConstraintName("FK_TicketOrder_Coupon");

            entity.HasOne(d => d.Member).WithMany(p => p.TicketOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketOrder_Member");

            entity.HasOne(d => d.OrderStatus).WithMany(p => p.TicketOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketOrder_OrderStatus");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.TicketOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketOrder_PaymentMethod");

            entity.HasOne(d => d.PaymentStatus).WithMany(p => p.TicketOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketOrder_PaymentStatus");
        });

        modelBuilder.Entity<TicketOrderItem>(entity =>
        {
            entity.HasKey(e => e.TicketOrderItemId).HasName("PK_航班訂單Detail");

            entity.HasOne(d => d.Schedule).WithMany(p => p.TicketOrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_航班訂單Detail_渡輪航班1");

            entity.HasOne(d => d.TicketOrder).WithMany(p => p.TicketOrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketOrderItem_TicketOrder");
        });

        modelBuilder.Entity<文章hashtag中介表>(entity =>
        {
            entity.HasOne(d => d.Hashtag編號Navigation).WithMany(p => p.文章hashtag中介表s)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_文章hashtag中介表_hashtag");

            entity.HasOne(d => d.文章編號Navigation).WithMany(p => p.文章hashtag中介表s)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_文章hashtag中介表_Article文章");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}