// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class MemberCouponList
{
    public int MemberCouponId { get; set; }

    public int MemberId { get; set; }

    public int CouponId { get; set; }

    public bool Used { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Member Member { get; set; }
}