// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Member
{
    public int MemberId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool? Gender { get; set; }

    public DateOnly Birthday { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public byte[] MemberPhoto { get; set; }

    public int? MemberLevelId { get; set; }

    public int MemberStatusId { get; set; }

    public virtual ICollection<Entourage> Entourages { get; set; } = new List<Entourage>();

    public virtual ICollection<ItineraryOrder> ItineraryOrders { get; set; } = new List<ItineraryOrder>();

    public virtual ICollection<MemberCouponList> MemberCouponLists { get; set; } = new List<MemberCouponList>();

    public virtual MemberLevel MemberLevel { get; set; }

    public virtual MemberStatus MemberStatus { get; set; }

    public virtual ICollection<MyCollection> MyCollections { get; set; } = new List<MyCollection>();

    public virtual ICollection<TicketOrder> TicketOrders { get; set; } = new List<TicketOrder>();
}