// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Member
{
    public int MemberId { get; set; }

    public string MemberName { get; set; }

    public string EnglishName { get; set; }

    public bool? Gender { get; set; }

    public DateTime? Birthday { get; set; }

    public int? CityId { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string ImagePath { get; set; }

    public int MemberLevelId { get; set; }

    public int MemberStatusId { get; set; }

    public bool GoogleLink { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<MemberCouponList> MemberCouponLists { get; set; } = new List<MemberCouponList>();

    public virtual MemberLevel MemberLevel { get; set; }

    public virtual MemberStatus MemberStatus { get; set; }

    public virtual ICollection<MyCollection> MyCollections { get; set; } = new List<MyCollection>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}