// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class Passenger
{
    public int PassengerId { get; set; }

    public int TicketOrderItemId { get; set; }

    public string PassengerLastName { get; set; }

    public string PassengerFirstName { get; set; }

    public string PassengerIdNumber { get; set; }

    public string PassportNumber { get; set; }

    public string PhoneNumber { get; set; }

    public virtual TicketOrderItem TicketOrderItem { get; set; }
}