// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class PortImage
{
    public int PortImageId { get; set; }

    public int PortId { get; set; }

    public byte[] PortImageUrl { get; set; }

    public string PortImageDescription { get; set; }

    public virtual Port Port { get; set; }
}