// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjJapanTravel_BackendMVC.Models;

[Table("TicketOrderItem")]
public partial class TicketOrderItem
{
    [Key]
    public int TicketOrderItemId { get; set; }

    public int TicketOrderId { get; set; }

    public int ScheduleId { get; set; }

    public int Quantity { get; set; }

    [InverseProperty("TicketOrderItem")]
    public virtual ICollection<Passenger> Passengers { get; set; } = new List<Passenger>();

    [ForeignKey("ScheduleId")]
    [InverseProperty("TicketOrderItems")]
    public virtual Schedule Schedule { get; set; }

    [ForeignKey("TicketOrderId")]
    [InverseProperty("TicketOrderItems")]
    public virtual TicketOrder TicketOrder { get; set; }
}