// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class TicketOrderItem
{
    public int TicketOrderItemId { get; set; }

    public int TicketOrderId { get; set; }

    public int ScheduleId { get; set; }

    public int Quantity { get; set; }

    public virtual ICollection<Passenger> Passengers { get; set; } = new List<Passenger>();

    public virtual Schedule Schedule { get; set; }

    public virtual TicketOrder TicketOrder { get; set; }
}