// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjJapanTravel_BackendMVC.Models;

public partial class 文章hashtag中介表
{
    public int 文章hashtag編號 { get; set; }

    public int 文章編號 { get; set; }

    public int Hashtag編號 { get; set; }

    public virtual Hashtag Hashtag編號Navigation { get; set; }

    public virtual Article文章 文章編號Navigation { get; set; }
}